### ISSUE TITLE
Trouble saving an Object due to Security Settings on unrelated fields

### ISSUE THREAD

**Issue by nickturrietta** [roblesterjr04/EloquentSalesForce#29]
Thanks for the great package! One issue I ran into and possible solution.

I tried to update the **Description** field on a **Case** object.

I received this error message.
`Salesforce response error: Client error: ``PATCH https://******.my.salesforce.com/services/data/v47.0/sobjects/Case/5006C000004ZWUGQA4`` resulted in a ``400 Bad Request`` response: [{"message":"Unable to create/update fields: LastModifiedDate, CreatedDate, ContactEmail. Please check the security settings...`

The culprit was that I had specified **LastModifiedDate**, **CreatedDate**, and **ContactEmail** in the **$columns** property on the **Case** model.

Even though I did not actively try to modify these properties, it looks they are still being passed to Salesforce as part of the patch request.

I'm not an expert but I think you can replace these 2 lines in **Model.php:76**

```php
$body = $this->attributes;
unset($body['attributes'], $body['Id']);
```

with this line in the patch request _(to only include the fields that have changed)_

```php
$body = $this->getDirty();
```

Thanks again! This package is helping us a lot.

**Comment by roblesterjr04** [comment]
Sorry for the late reply!!! This should be fixed on the latest release, i encountered it myself last week.

Please upgrade to `^2.3`

Thanks!!!!

**Comment by nickturrietta** [comment]
Hey Rob. I'm on v2.5. This is still an issue it seems. I'm trying to change a single field on an object, but the PATCH request is acting like a PUT request and is trying to change a bunch of unrelated fields on the object.

This would be the quick fix as far as I can see...

Change:
```php
public function writeableAttributes($exclude = [])
{
    $fields = array_merge($this->readonly, $exclude);
    return Arr::except($this->attributes, $fields);
}
```

To:
```php
public function writeableAttributes($exclude = [])
{
    $fields = array_merge($this->readonly, $exclude);
    return Arr::except($this->getDirty(), $fields);
}
```

For what it's worth.

**Comment by roblesterjr04** [comment]
I’ll take a look and try these suggestions next week. Thank you for raising.

**Comment by roblesterjr04** [comment]
Hmm, when I do that, it causes problems for the mass update method. I will need to be thoughtful about how to implement this.

**Comment by nickturrietta** [comment]
Aw copy that. I hadn't tested with mass updates. Interesting that it would have an effect on it actually. All good.

**Comment by RipleWare** [comment]
Hi there, just wondering if this was ever resolved, as I have now encountered this issue once introducing `LastModified` into my model.

This package is working very well for me, however, I now need to get around this issue if I can.
Thanks.
